### ISSUE TITLE
Issue with highlighting (possibly counting) of upper case searches

### ISSUE THREAD

**Issue by slstaples** [writecrow/crow_backend#34]
When I conduct the search for "First", the top level excerpt results seem to be all uppercase, but there are lowercase items highlighted in the text when I click on a text. I feel like we had something similar to this in the past?...

**Comment by markfullmer** [comment]
Thanks for reporting this, @slstaples . 

I'm able to reproduce the bug -- example: https://crow.corporaproject.org/corpus/106i_AB_1_CHN_1_M_10314_PRD?search=%22First%22&method=word

I can't recall if we encountered this bug exactly -- case insensitive results showing up on the individual text pages -- but it should be relatively straightforward to debug, and it should be added to our test suite so that we'll know it doesn't regress in the future.

**Comment by markfullmer** [comment]
Hi @slstaples , 

I've staged a code change that resolves the non-case-sensitive highlighting in the keyword-in-context display, per #35 . I also confirmed that the issue was limited to the display highlight in this context, not a larger counting issue.

When you have a chance, can you verify that things look correct in the development environment.

Example searches in the development site (fixed):
- [x] "First" (quoted) : https://devcrow.corporaproject.org/corpus/106i_AB_1_CHN_1_M_10314_PRD?search=%22First%22&method=word
- [x] First (unquoted): https://devcrow.corporaproject.org/corpus/106i_AB_1_CHN_1_M_10314_PRD?search=First&method=word
- [x] "first article" (phrase): https://devcrow.corporaproject.org/corpus/106i_AB_1_CHN_1_M_10314_PRD?search=%22first%20article%22&method=word
- [x] first article (separate words): https://devcrow.corporaproject.org/corpus/106i_AB_1_CHN_1_M_10314_PRD?search=first%20article&method=word

Baseline searches in the production site (not yet deployed):
- [ ] "First" (quoted) : https://crow.corporaproject.org/corpus/106i_AB_1_CHN_1_M_10314_PRD?search=%22First%22&method=word
- [x] First (unquoted): https://crow.corporaproject.org/corpus/106i_AB_1_CHN_1_M_10314_PRD?search=First&method=word
- [x] "first article" (phrase): https://crow.corporaproject.org/corpus/106i_AB_1_CHN_1_M_10314_PRD?search=%22first%20article%22&method=word
- [x] first article (separate words): https://crow.corporaproject.org/corpus/106i_AB_1_CHN_1_M_10314_PRD?search=first%20article&method=word
